version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY:-}
      - PORT=8000
    restart: unless-stopped
    volumes:
      - .:/app